### ISSUE TITLE
How to set fetch.message.max.bytes config in the SimpleConsumer?

### ISSUE THREAD

**Issue by scootli** [mumrah/kafka-python#285]
My message size is too small. now One partition is about 20MB/sec. When I set the fetch.message.max.bytes config to 3MB instead of 1MB in the SimpleConsumer with C++, I find the throughput is double. The problem is:
How to set fetch.message.max.bytes config in the SimpleConsumer in the kafka-python? I don't find the config parameter. what do I miss?

Thanks

**Comment by jettify** [comment]
Hi scootli,
Looks like you need to set ``buffer_size`` variable in *SimpleConsumer* constructor since this value is used in ``FetchRequest`` struct [0], and remember to increase ``max_buffer_size`` too. *SimpleConsumer* try to adjust buffer if message is to large but up to ``max_buffer_size`` [1].

[0] https://github.com/mumrah/kafka-python/blob/master/kafka%2Fconsumer%2Fsimple.py#L277-L284
[1] https://github.com/mumrah/kafka-python/blob/master/kafka%2Fconsumer%2Fsimple.py#L300-L313

**Comment by scootli** [comment]
I get it. Thanks
