### ISSUE TITLE
Support for Kafka 0.8.3

### ISSUE THREAD

**Issue by kenfar** [mumrah/kafka-python#305]
Does the kafka-python module support Kafka 0.8.3?

**Comment by dpkp** [comment]
kafka 0.8.3 doesn't exist, so assume you mean 0.8.2 that is about to be released

compatibility details are listed in the README here: https://github.com/mumrah/kafka-python#status

summary: 0.8.0, 0.8.1, and 0.8.1.1 are supported.  We expect to support 0.8.2 when it is released.

Note that kafka-python will *not* work with the 0.8.2-beta server release due to server-side protocol bugs.  those bugs are resolved in the latest 0.8.2 server release candidate, and so we expect to support 0.8.2 when it is released, though "support" here would mean kafka-python clients should continue to work not that all new server features can be accessed via kafka-python immediately.
