### ISSUE TITLE
Kafka-python does not connect to zookeeper but the kafka nodes

### ISSUE THREAD

**Issue by amitpl** [mumrah/kafka-python#308]
Hi All,

I am currently using kafka-python in my application.
I found out that kafkaClient is connecting to kafka nodes instead of zookeeper, while in a Java Client the connection is made to zookeeper and kafka cluster information is provided by zookeeper.

My Questions:
1. Is kafka-python unaware of zookeeper nodes and directly communicate with kafka nodes (seems unlikely as consumer offset is stored in zookeeper)
2. Why don't we create the client by giving zookeeper connection string instead of kafka connection string.

Thanks,

**Comment by mrtheb** [comment]
1. kafka-python doesn't deal with zookeeper. The design was always made in a such way that it uses the kafka [offset commit API](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommit/FetchAPI).
2. Broker and topic discovery can be achieved with the Kafka metadata API w/o having to rely on Zookeeper for the same purpose.

If you ask yourself how the consumer rebalance would work w/o zookeeper, the answer is the kafka-python library sits somewhere near the SimpleConsumer in terms of functionalities. But as the [Kafka Consumer Redesign](https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Client+Re-Design) will evolve, the kafka-python library will actually be closer to the new implementation.

**Comment by amitpl** [comment]
Aah... that makes sense !!!

**Comment by samrusk** [comment]
Hey Guys,

I have a similar question. 
I understand that the consumers and producers are able to connect to the kafka-servers without knowledge of the zookeeper due to new rebalancing.  However,  I am wondering if there is anyway to start the zookeeper server or the kafka server from within the kafka-python library.  

Currently, I am using the command line shell's to start the zk and kafka-servers but would like to get it inside my python code if possible.  

If you have any thoughts or you might be doing this already, all help would be greatly appreciated.

Thanks!

**Comment by mumrah** [comment]
@samrusk you can look at how we start up Kafka and ZooKeeper in https://github.com/mumrah/kafka-python/blob/master/test/fixtures.py, though I wouldn't recommend doing it this way in a production setting.

If you want to control things like starting/stopping servers from Python, I would check out Fabric or Ansible

**Comment by Gowtham95india** [comment]
@mrtheb 

Let's say I'm using 3 brokers and I mentioned them in my kafka producer. Later I increased brokers to 6. My topic as 3 replicants and 10 partitions (automatically assigned). 

1. Is that fine, even If I add 1 broker to kafka-python?

2. What happens if the broker I mentioned in kafka-python is down? Does kafka-python will continue with remaining brokers?

3. Does kafka python will be aware of the newly added brokers ?

4. If I need to add them manually in kafka-python code, why not using zookeeper then? Because my kafka-python has to do very rapid processing, so I don't want it to be down ever.
