### ISSUE TITLE
kafka.common.UnknownError

### ISSUE THREAD

**Issue by futurekill** [mumrah/kafka-python#311]
Hi,

We recently upgraded our kafka cluster to 0.8.2. Prior to the upgrade my consumer was working just fine but now I get the following error:
kafka.common.UnknownError: OffsetFetchResponse(topic='topic', partition=0, offset=-1, metadata='', error=16)

Anyone know what could be going on?

The python consumer I'm using is just for testing. We have another one we using in production written in scala that is working just fine so this ins't really affecting anything important.

**Comment by dpkp** [comment]
are you on 0.8.2-beta or one of the release candidates? (there were significant compatibility issues with the beta -- kafka-python is known to fail against the beta candidate)

what version of kafka-python are you using?

if you use kafka-python trunk / master from git, and the ofificial kafka server 0.8.2.0 from https://archive.apache.org/dist/kafka/0.8.2.0/ I do not think you will see that error

**Comment by futurekill** [comment]
We're using 0.8.2-beta (the on linked to on the kafka homepage).

I was using the 0.9.2 but I've also tried a version from master in a virtualenv. Neither worked.

I'll try upgrading to 0.8.2 official.I wish they had that listed on the main page.

**Comment by dpkp** [comment]
ok, that makes sense.  you cannot avoid errors from the 0.8.2-beta release on any kafka-python codebase, so master branch against 0.8.2-beta will still throw that error.  the beta server includes incompatible changes to the binary API protocols that had to be reverted / fixed.  the official 0.8.2.0 isn't actually released on the download page yet because the release vote just passed on the mailing list yesterday.  you should expect to see apache release announcement today or in the next couple of days.

we're expecting to release a new version of kafka-python today/tomorrow to pypi that will support the 0.8.2.0 release, so stay tuned!

**Comment by futurekill** [comment]
Thanks for the quick reply by the way...:)

**Comment by kjelle** [comment]
@dpkp: I experience the same issue. I'v tested both branch:master and branch:v0.9.4 against Kafka 0.8.2.2.3 (HDP 2.3).

It is the consumer which seems to be the issue. I am able to use KafkaClient and KafkaConsumer but SimpleConsumer fails in any way.

It returns error=16 on the OffsetFetchResponse.

**Comment by toddpalino** [comment]
Pull request #420 has been available for months to fix this. The problem is that the client does not properly perform a ConsumerMetadataRequest to determine which broker is the correct one to talk to for the OffsetCommitRequest and OffsetFetchRequest calls.
